"""revisão inicial

Revision ID: 266f470c2c27
Revises: 
Create Date: 2023-03-22 17:58:41.213019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266f470c2c27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password2', sa.String(), nullable=True))
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_lastusername'), 'usuario', ['lastusername'], unique=False)
    op.create_index(op.f('ix_usuario_makeuser'), 'usuario', ['makeuser'], unique=False)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_makeuser'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_lastusername'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_column('usuario', 'password2')
    # ### end Alembic commands ###
