"""revisão atualizada

Revision ID: 630baedfb1a6
Revises: 266f470c2c27
Create Date: 2023-03-24 14:49:07.457925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630baedfb1a6'
down_revision = '266f470c2c27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_usuario_makeuser', table_name='usuario')
    op.create_index(op.f('ix_usuario_makeuser'), 'usuario', ['makeuser'], unique=True)
    op.create_index(op.f('ix_usuario_password'), 'usuario', ['password'], unique=False)
    op.create_index(op.f('ix_usuario_password2'), 'usuario', ['password2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_password2'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_password'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_makeuser'), table_name='usuario')
    op.create_index('ix_usuario_makeuser', 'usuario', ['makeuser'], unique=False)
    op.drop_column('usuario', 'hashed_password')
    # ### end Alembic commands ###
